language: python
services:
  - docker
env:
  global:
    - IMAGE_NAME=aau/ctfd
    - VERSION=1.2.0
    - REGISTRY_HOST=registry.sec-aau.dk
    - REGISTRY_USER=travis
    - REGISTRY_PASS=T5CBgSJfMfJfUAyreMBHz96DhFE89ADK
  matrix:
    - TESTING_DATABASE_URL='sqlite://'
python:
  - 3.6
install:
  - pip install -r development.txt
before_script:
  - python tests/helper_virt_server.py || true > /dev/null 2>&1 &
script:
  - pep8 --ignore E501,E712 --exclude "helper_virt_server.py" CTFd/ tests/ 
  - nosetests -v -d --with-randomly
after_success:
  - codecov
before_deploy:
  - docker login "$REGISTRY_HOST" -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" -f Dockerfile .
  - docker tag "$IMAGE_NAME" "${REGISTRY_HOST}/${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${REGISTRY_HOST}/${IMAGE_NAME}:${VERSION}"
deploy:
  provider: script
  script: docker push "${REGISTRY_HOST}/${IMAGE_NAME}:latest" && docker push "${REGISTRY_HOST}/${IMAGE_NAME}:${VERSION}" 
  on:
    branch: master
