language: python
services:
    - mysql
env:
    - TESTING_DATABASE_URL='mysql+pymysql://root@localhost/ctfd'
    - TESTING_DATABASE_URL='sqlite://'
python:
    - 2.7
    - 3.6
install:
    - pip install -r development.txt
script:
    - pep8 --ignore E501,E712 CTFd/ tests/
    - nosetests
