version: '2'

services:
  ctfd:
    restart: always
    container_name: ctfd
    build: .
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    ports:
      - "8000:8000"
    volumes:
      - ./${CTFD_DATA_DIR}/CTFd/logs:/opt/CTFd/CTFd/logs
      - ./${CTFD_DATA_DIR}/CTFd/uploads:/opt/CTFd/CTFd/uploads
    depends_on:
      - db

  db:
    restart: always
    container_name: db
    image: postgres:alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    expose:
      - "5432"
    volumes:
      - ./${POSTGRES_DATA_DIR}:/var/lib/postgresql
